include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - 'lib/db/migrations/'
    - 'lib/view/autocomplete.dart'
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    avoid_print: false
    lines_longer_than_80_chars: false
    prefer_single_quotes: true
    use_build_context_synchronously: false
