targets:
  freezed_only:
    auto_apply_builders: false
    builders:
      freezed:
        enabled: true
  $default:
    dependencies: [ ":freezed_only" ]
    builders:
      drift_dev:
        options:
          apply_converters_on_variables: true
          generate_values_in_copy_with: true
          named_parameters: true
          override_hash_and_equals_in_result_sets: true
          generate_connect_constructor: true
          store_date_time_values_as_text: true
          write_to_columns_mixins: true
      freezed:
        enabled: false
        options:
          union_key: type
          union_value_key: snake
      json_serializable:
        options:
          any_map: true
          explicit_to_json: true
          field_rename: snake