name: netrunner_deckbuilder
description: 'An Android: Netrunner Deckbuilder'

publish_to: 'none'

version: 1.1.2+20

environment:
  sdk: ^2.17.0

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: any
  chips_input: any
  collection: any
  connectivity_plus: any
  diacritic: any
  drift: any
  dotenv_gen: ^0.0.1
  flutter_appauth: any
  flutter_cache_manager: any
  flutter_riverpod: any
  flutter_secure_storage: any
  flutter_sticky_header: any
  freezed: any
  freezed_annotation: any
  http: any
  kotlin_flavor: any
  path_provider: any
  path: any
  petitparser: any
  query:
    path: ../query
  rxdart: any
  sqlite3_flutter_libs: any
  timeago: any
  url_launcher: any
  uuid: any

dev_dependencies:
  build_runner: any
  drift_dev: any
  dotenv_gen_runner:
    path: ../env_gen/dotenv_gen_runner
  flutter_gen_runner: any
  flutter_launcher_icons: any
  flutter_lints: any

dependency_overrides:
  flutter_riverpod:
    path: ../river_pod/packages/flutter_riverpod
  riverpod:
    path: ../river_pod/packages/riverpod
  drift:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: drift
  drift_dev:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: drift_dev
  sqlparser:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: sqlparser
  sqlite3_flutter_libs:
    git:
      url: https://github.com/simolus3/sqlite3.dart.git
      ref: main
      path: sqlite3_flutter_libs

flutter_icons:
  ios: true
  macos: true
  windows: true
  image_path: assets/icons/app-ios.png

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/nrdb/

flutter_gen:
  output: lib/util/

scripts: scripts.yaml