name: netrunner_deckbuilder
description: 'An Android: Netrunner Deckbuilder'

publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: any
  chips_input: any
  connectivity_plus: any
  drift: any
  envify: any
  flutter_appauth: any
  flutter_cache_manager: any
  flutter_dotenv: any
  flutter_html: 3.0.0-alpha.2
  flutter_riverpod: 2.0.0-dev.4
  flutter_secure_storage: any
  flutter_sticky_header: any
  freezed: any
  kotlin_flavor: any
  path_provider: any
  path: any
  query: any
  rxdart: any
  sqlite3_flutter_libs: any
  timeago: any
  uuid: any
  url_launcher: any

dev_dependencies:
  build_runner: any
  drift_dev: any
  envify_generator: any
  flutter_gen_runner: any
  flutter_launcher_icons: any
  flutter_lints: any
  http: any

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icons/app.png

dependency_overrides:
  sqlparser:
    git:
      url: https://github.com/simolus3/moor.git
      ref: develop
      path: sqlparser
  drift:
    git:
      url: https://github.com/simolus3/moor.git
      ref: develop
      path: drift
  drift_dev:
    git:
      url: https://github.com/simolus3/moor.git
      ref: develop
      path: drift_dev

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/nrdb/

flutter_gen:
  output: lib/util/

scripts: scripts.yaml